### ISSUE TITLE
Hello. Some questions..

### ISSUE THREAD

**Issue by sparcbr** [Samshal/Scripd#11]
FIrstl, thanks for this. I think it might be quite useful.

I never heard of jsyn. Is this a standard? If yes where is it from? I couldn't find the origins of it.

Is there a tool to make the opposite, connect to the database or read a SQL and generate the jsyn json?

Thanks!

**Comment by Samshal** [comment]
Thank you.

No, jsyn is not a documented standard anywhere. It works though, the idea is have a set of "standards" and scripd will build its workflow around that.

No, there's no tool for the opposite, but sounds like something interesting to build. Would you be interested in this?
